Sprint 11
maxim-papier/gallery pull request #15
Opened 2023-01-22 07:31 UTC by maxim-papier

1. [DONE] Потенциальные гонки, которые могут возникнуть при выполнении POST-запроса на получение Auth Token от Unsplash, устранены двумя способами — с помощью отмены запроса и с помощью блокировки UI.
2. [DONE] Сделан сетевой слой для экрана профиля.
3. [DONE] Есть индикатор загрузки на запрос токена после регистрации.

2023-01-22 14:41 UTC, mmbabaev requested changes

2023-01-22 14:41 UTC, mmbabaev commented on Gallery/AppDelegate.swift
> +        // return UISceneConfiguration(name: "Default Configuration", sessionRole: connectingSceneSession.role)
удалить закомментированный код

2023-01-22 14:41 UTC, mmbabaev commented on Gallery/Constants.swift
> +    static let getTokenURLPath = "/oauth/token"
тк это название переменных, лучше не называть их с `get`

2023-01-22 14:41 UTC, mmbabaev commented on Gallery/Models/UserResult.swift
> +        case profileImage = "profile_image"
еще для информации: скорее всего тут подойдет использовать `keyDecodingStrategy`
https://developer.apple.com/documentation/foundation/jsondecoder/keydecodingstrategy

2023-01-22 14:41 UTC, mmbabaev commented on Gallery/Scenes/Profile/ProfileViewController.swift
> +    var avatar = UIImageView()
можно let для всех UIView

2023-01-22 14:41 UTC, mmbabaev commented on Gallery/Scenes/Profile/ProfileViewController.swift
> +    let token = OAuth2TokenStorage().token
добавить private

2023-01-22 14:41 UTC, mmbabaev commented on Gallery/Scenes/Profile/ProfileViewController.swift
> +        /// Name
вы помечаете секции кода комментариями, это лучше, чем без них, но еще лучше будет вынести отдельные функции

2023-01-22 14:41 UTC, mmbabaev commented on Gallery/Scenes/Profile/ProfileViewController.swift
> +// MARK: - UI updates section
для чего мы выносим прямо каждую приватную функцию в отдельный extension? Обычно функции выделяют в extension, если они чем-то объединены (private функции, функции протокола)

2023-01-22 14:41 UTC, mmbabaev commented on Gallery/Scenes/SplashViewController/SplashViewController.swift
> +enum SplashError: String {
я бы ожидал `enum SplashError: Error, String` здесь. Дальше можно реализовать `LocalizedError`

2023-01-22 14:41 UTC, mmbabaev commented on Gallery/Scenes/SplashViewController/SplashViewController.swift
> +    override func viewDidLoad() {
удалить, если здесь ничего не происходит кроме вызова super метода

2023-01-22 14:41 UTC, mmbabaev commented on Gallery/Scenes/SplashViewController/SplashViewController.swift
> +    private var tokenStorage = OAuth2TokenStorage()
let

2023-01-22 14:41 UTC, mmbabaev commented on Gallery/Scenes/SplashViewController/SplashViewController.swift
> +            // is NOT logged in
эти комментарии не несут доп информации, суть понятна из условия в if

2023-01-22 14:41 UTC, mmbabaev commented on Gallery/Scenes/SplashViewController/SplashViewController.swift
> +import ProgressHUD
вы сделали класс-обертку для этой библиотеки, не нужно везде импортировать ее

2023-01-22 14:41 UTC, mmbabaev commented on Gallery/Scenes/SplashViewController/SplashViewController.swift
> +        ProfileImageService.shared.fetchProfileImageURL(username: username!) { _ in }
не делайте форс анрап

2023-01-22 14:56 UTC, maxim-papier commented on Gallery/Scenes/SplashViewController/SplashViewController.swift
> +    private var tokenStorage = OAuth2TokenStorage()
Я на 119 строке записываю `self.tokenStorage.token = token`, тогда будет ошибка.

2023-01-22 14:58 UTC, mmbabaev commented on Gallery/Scenes/SplashViewController/SplashViewController.swift
> +    private var tokenStorage = OAuth2TokenStorage()
понял, окей. Думал там класс

2023-01-22 15:03 UTC, maxim-papier commented on Gallery/AppDelegate.swift
> +        // return UISceneConfiguration(name: "Default Configuration", sessionRole: connectingSceneSession.role)
Готово. Спасибо.

2023-01-22 15:04 UTC, maxim-papier commented on Gallery/Scenes/Profile/ProfileViewController.swift
> +    var avatar = UIImageView()
Готово.

2023-01-22 15:05 UTC, maxim-papier commented on Gallery/Scenes/SplashViewController/SplashViewController.swift
> +        ProfileImageService.shared.fetchProfileImageURL(username: username!) { _ in }
Исправлено

2023-01-22 15:12 UTC, maxim-papier commented on Gallery/Scenes/Profile/ProfileViewController.swift
> +// MARK: - UI updates section
Принято. Справедливо. Спасибо.

2023-01-22 15:23 UTC, maxim-papier commented on Gallery/Scenes/Profile/ProfileViewController.swift
> +        /// Name
Сделано

2023-01-22 15:28 UTC, maxim-papier commented on Gallery/Scenes/SplashViewController/SplashViewController.swift
> +enum SplashError: String {
Сделано. Спасибо.

2023-01-23 13:28 UTC, maxim-papier commented
У меня была проблема с алертом, он вообще не выводился на экран. Исправил. Равно как и другие замечания. Спасибо.

2023-01-24 14:39 UTC, merged