Sprint 12
maxim-papier/gallery pull request #16
Opened 2023-01-26 18:11 UTC by maxim-papier

1. [ ]  ✅ Приложение запускается, не падает в RunTime, нет retain cylces
    
2. [ ]  В проекте реализована постраничная загрузка данных для ленты фотографий
    
    - [ ]   ✅ добавлена структура для ответа от Unsplash — `PhotoResult`, вспомогательная структура `UrlsResult`;
        
    - [ ]   ✅ создана структура `Photo` для UI слоя;
        
    - [ ]   ✅ при получении ответа из сети формируется объект `Photo` для каждого `PhotoResult`;
        
    - [ ]   ✅ создан новый класс `ImagesListService`;
        
    - [ ]   ✅ добавлено свойство `photos: [Photo]` для хранения последовательности всех загруженных из сети фотографий;
        
    - [ ]   ✅ в `ImagesListService` добавлена нотификация `static let DidChangeNotification = Notification.Name(rawValue: "ImagesListServiceDidChange")`;
        
    - [ ]   в классе `ImagesListService` объявлена функция `fetchPhotosNextPage()`, которая загружает очередную страницу; при этом —
        
        - [ ]   ✅ функция внутри себя определяет номер следующей страницы для закачки (номер не должен сообщаться извне, как параметр функции);
        - [ ]   ✅ если идёт закачка, то нового сетевого запроса не создаётся, а выполнение функции прерывается;
        - [ ]   ✅ при получении новых фотографий массив `photos` обновляется из главного потока, а новые фото добавляются в конец массива;
        - [ ]   ✅ после обновления значения массива `photos` публикуется нотификация `ImagesListService.DidChangeNotification`.
        - [ ]   ✅ написана функция `updateTableViewAnimated()`, вызвана с `ImagesListService.DidChangeNotification` и будет анимированно обновляет таблицу.
3. [ ]  Реализован функционал лайков:
    
    - [ ]   ✅ создана и активна кнопка с картинками-сердечками (`UIButton`);
    - [ ]   ✅ кнопка с индикатором размещена в ячейке таблицы, присутствует на каждой картинке;
    - [ ]   ✅ в ячейку добавлен метод `setIsLiked`, который изменяет состояние лайка;
    - [ ]   ✅ созданы `@IBAction` для реакции тапа по лайку и `@IBOutlet` для кнопки;
    - [ ]   ✅ обработана ситуация сетевой гонки с помощью блокирования UI интерфейса.
4. [ ]  При тапе на картинку в общем списке изображений должен осуществляться переход на экран, где можно посмотреть полноразмерную версию фотографии (также фото можно зумить):
    
    - [ ]   ✅ для отображения картинки использован `UIImageView`;
    - [ ]   ✅ для просмотра картинки в масштабе использован `UIScrollView`;
    - [ ]   ✅ на время загрузки картинки показывается плейсхолдер и лоадер загрузки (используйте `ProgressHUD`);
    - [ ]   ✅ реализован парсинг поля со ссылкой на полноразмерную картинку;
    - [ ]   ✅ чтобы просматривать выбранную картинку из списка, реализован переход на новый контроллер;
    - [ ]   ✅ новому контроллеру для отображения выбранной картинки нужна передача информации о ней;
    - [ ]   ✅ реализована кнопка «Назад» для возвращения к списку картинок.
5. [x]  Добавлена возможность выхода из аккаунта:
    
    - [x]   ✅ удаляется значение `authToken` из `OAuth2TokenStorage`;
    - [x]   ✅ очищаются куки (cookie) веб-браузера (вызван `HTTPCookieStorage.shared.removeCookies(since: .distantPast)`);
    - [x]   ✅ `rootViewController` заменяется на `SplashViewController`.

2023-01-27 19:46 UTC, ABashkirova commented on Gallery/Scenes/ImagesList/ImagesListCell.swift
> +        let image = isLiked == true ? UIImage(named: "likeButton_isActive") :
`isLiked == true` аналогично просто `isLiked`, поэтому можно упростить:
```suggestion
        let image = isLiked ? UIImage(named: "likeButton_isActive") :
```

2023-01-27 20:05 UTC, IBDesignable requested changes

2023-01-28 02:41 UTC, maxim-papier commented on Gallery/Scenes/ImagesList/ImagesListViewController.swift
> +
Прошу прощения. Последствия рефакторинга. У меня очень сжатые сроки: дали время со среды до понедельника на два спринта (12 и 13) и я не успел "причесать". Убрал.

2023-01-28 02:50 UTC, maxim-papier commented on Gallery/Scenes/Profile/ProfileViewController.swift
> +        OAuth2TokenStorage.clean()
Готово

2023-01-28 03:16 UTC, maxim-papier commented on Gallery/Scenes/SingleView/SingleImageViewController.swift
> +                }
Сделано

2023-01-28 04:11 UTC, maxim-papier commented on Gallery/Services/ImageListService.swift
> +        let nextPage = lastLoadedPage == nil ? 1 : lastLoadedPage! + 1
Выполнено. Разучился!

2023-01-28 04:52 UTC, maxim-papier commented
Александра, спасибо. Всегда рад, когда попадаю на ревью к вам. Оставил одно из ваших замечания на будущее, так как надо спешить. 13 спринт сложный, а у меня два дня. Остальное сделал. Снова отправляю работу через практикум. Хороших вам выходных.

2023-01-28 20:30 UTC, IBDesignable approved these changes

2023-01-28 20:30 UTC, IBDesignable commented on Gallery/Helpers/Alert.swift
> +    }
Вообще здесь этот код не ожидаешь увидеть. Лучше прямо рядом с профилем положить. Иначе любой вью контроллер может вдруг тебя разлогинить – слишком много доступа

2023-01-28 20:30 UTC, IBDesignable commented on Gallery/Services/ImageListService.swift
>      }()
ок, только если тебе не нужно его преднастраивать, можно без замыканий обойтись, в одну строчку проиницилазировать.

2023-01-28 20:43 UTC, maxim-papier commented on Gallery/Helpers/Alert.swift
> +    }
Спасибо! Вынесу себе это в доработки на будущее. У меня просто уже 13 спринт процентов на 70 сделан и я его самоуверенно смёрджил ещё днём, с той версией 12-го, которая у вас была на ревью. ;) Сейчас доработки 12-го меня доканают.

2023-01-28 20:45 UTC, maxim-papier commented on Gallery/Services/ImageListService.swift
>      }()
Это сделал

2023-01-28 20:46 UTC, merged