Sprint 13
maxim-papier/gallery pull request #23
Opened 2023-01-30 19:12 UTC by maxim-papier

2023-01-31 19:06 UTC, IBDesignable requested changes

2023-01-31 19:06 UTC, IBDesignable commented on Gallery/Scenes/Profile/ProfilePresenter.swift
> +    var view: ProfileViewControllerProtocol?
weak

2023-01-31 19:06 UTC, IBDesignable commented on Gallery/Scenes/Profile/ProfilePresenter.swift
> +    let profileImageService = ProfileImageService.shared
Они нужны для тестов? давай все что не нужно не закрыто ProfilePresenterProtocol закроем приватными модификаторами

2023-01-31 19:08 UTC, IBDesignable commented
В пул реквест не попал код из чеклиста. Будь пожалуйста аккуратнее с комитами

2023-02-01 01:44 UTC, maxim-papier commented on Gallery/Helpers/GradientKFIndicator.swift
> +//    }
Ай, стыдоба какая.

2023-02-01 01:46 UTC, maxim-papier commented on Gallery/Helpers/GradientView.swift
> +//        gradient.frame = self.bounds
Всё понял. Я экспериментировал и удалил файлы, но, видимо, как-то неправильно — в Xcode мне  их не видно. 

Удалил вручную через Finder.

2023-02-01 02:06 UTC, maxim-papier commented on GalleryTests/Profile/ProfileViewTest.swift
> +        ///given
Спасибо. Очень интересно про документацию. Исправил.

2023-02-01 11:05 UTC, maxim-papier commented on Gallery/Scenes/ImagesList/ImagesListPresenter.swift
> +import UIKit
Совсем что-то не вышло избавиться. updateTableViewAnimated() метод никак не растащу между презентером и вьюконтроллером.

2023-02-01 11:06 UTC, maxim-papier commented on Gallery/Scenes/ImagesList/ImagesListPresenter.swift
> +        self.dateFormatter.timeStyle = .none
Отложил себе в issues

2023-02-01 11:18 UTC, maxim-papier commented
Добрый день, Александра. Спасибо за ваши замечания. Приношу свои извинения за неаккуратную работу. Я очень спешил. Мне поставили дедлайн до конца понедельника и я сделал пулрееквест прямо в притык. 

Я исправил то, что мог. Посмотрите, пожалуйста, требуется ли ещё доработки?

2023-02-01 16:42 UTC, IBDesignable commented on Gallery/Scenes/ImagesList/ImagesListPresenter.swift
> +import UIKit
Окей, это действительно может быть не тривиально сейчас, поэтому я и написала стремиться. 

Оставь как есть

2023-02-02 11:26 UTC, IBDesignable commented on Gallery/Scenes/TabBarController.swift
> +        presenter1.view = vc1
Не приветствуются именования 1 и 2, ничего страшного не произойдет если ты напишешь полное название imageListService, imageListPresenter

Но если правда лень – тогда хотя бы выноси в отдельные функции – assembleImageListModule -> UIViewController 

На самом деле подход с фабричными методами близко к продакшену будет :) asseble/build/create глаголы которые чаще всего в таком коде можно встретить

2023-02-02 13:17 UTC, maxim-papier commented on Gallery/Scenes/TabBarController.swift
> +        presenter1.view = vc1
Я не ленился, а пытался сократить —очень не люблю длиннющие имена. :) Больше так не буду. Спасибо.

2023-02-02 13:17 UTC, merged

2023-02-03 07:26 UTC, IBDesignable commented on Gallery/Scenes/TabBarController.swift
> +        presenter1.view = vc1
мне тоже так по первости казалось, а потом оказалось что лучше длинные, чтобы было понятно из любой точки кода